# coding: utf-8
"""Client-side private config.

Generated by `bigqmt-init`.
DO NOT COMMIT: this file holds an account id and Redis credentials.
"""

BIGQMT_ACCOUNT_ID = '52625295'
BIGQMT_RPC_TIMEOUT_SECONDS = 30.0

BIGQMT_REDIS_CONFIG = {
    # 2026-09-23: zmq 是旧代值；现役桥=shm（与服务端 local_config 一致）。
    "transport": 'shm',
    "host": '127.0.0.1',
    "port": 15655,
    "db": 5,
    "username": '',
    "password": '',
    # QMT host/port are explicit so RPC and quote-push clients use the
    # same machine. The server config generated alongside this file
    # binds loopback for local use or 0.0.0.0 for a remote QMT host.
    "zmq": {
        "host": '127.0.0.1',
        "port": 15655,
        "connect_address": "tcp://127.0.0.1:15655",
    },
}

# Reference/history reads go straight to Big QMT's FormulaServer (port
# 58600) instead of over RPC. Every miss falls back to RPC, so an
# unreachable 58600 changes nothing.
# ⚠️ 2026-09-23: enabled 必须 False——这条直连是回环 TCP，模型交易面板
# 运行期间会被终端审计记非法IP并全面板杀策略（实锤 illegal IP:127.0.0.1:60470）。
# 要测 fastpath 数字先停面板里的桥。
BIGQMT_FORMULA_SERVER_CONFIG = {
    "enabled": False,
}

BIGQMT_LOCAL_CACHE_CONFIG = {
    "enabled": True,
    "dir": None,
    "fallback_rpc": True,  # MiniQMT-compatible adjusted reads; False = offline only
    "format": "auto",
}
